# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ee-W9QNP2mxTJJ7CdAMtnkxhEMZ36cHV
"""

import statistics

exam_scores = [78, 85, 90, 88, 76, 95, 89, 92, 85, 87]

mean_value = statistics.mean(exam_scores)
median_value = statistics.median(exam_scores)
mode_value = statistics.mode(exam_scores)

variance = statistics.variance(exam_scores)
standard_deviation = statistics.stdev(exam_scores)

print("Mean (Average score):", mean_value)
print("Median (Middle score):", median_value)
print("Mode (Most Frequent):", mode_value)
print("Variance (Score Spread):", variance)
print("Standard Deviation (Score Deviation):", standard_deviation)
